# Generated by Django 4.1.3 on 2022-12-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="client",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="client",
            new_name="customer",
        ),
    ]
