# Generated by Django 4.1.3 on 2022-12-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0003_rename_client_contract_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="event_contract",
                to="crm_app.event",
            ),
        ),
    ]
