# Generated by Django 4.1.3 on 2022-12-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0005_event_sales_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="sales_contact",
        ),
        migrations.AddField(
            model_name="event",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="event_contract",
                to="crm_app.contract",
            ),
        ),
    ]
