# Generated by Django 4.1.3 on 2022-12-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0006_remove_event_sales_contact_event_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False, verbose_name="SIGNED"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.BooleanField(default=False, verbose_name="FINISHED"),
        ),
    ]
