# Generated by Django 4.1.3 on 2022-12-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0007_alter_contract_status_alter_event_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False, verbose_name="check if signed"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.BooleanField(default=False, verbose_name="check if finished"),
        ),
    ]
