# Generated by Django 4.1.4 on 2022-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0008_alter_contract_status_alter_event_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Signed"),
        ),
    ]
